### ISSUE TITLE
Outlook support

### ISSUE THREAD

**Issue by vitt0** [milad00ahmadi/freehost-anti-phishing#1]
Hi there, 

I'm really interest in using this anti phishing script, but in my case I mostly have account that try to steal account of Outlook, could you please add support for it?

![HCJYbjw](https://user-images.githubusercontent.com/11968934/126844874-b0627f36-7c5d-4b29-94ad-c1746fc43a21.png)

**Comment by milad00ahmadi** [comment]
Hi
I'm so happy that it attracts your attention, I will add outlook within a few days
